### ISSUE TITLE
musl build failure

### ISSUE THREAD

**Issue by helmutg** [SELinuxProject/selinux#476]
This is continuing the story of ABI-duality for Debian's time64 implementation in `matchpathcon_filespec_add`. The last fallout was a build failure on glibc-x32 in #463. While that was fixed, we now face a build failure on musl.

The way that x32 issue was fixed relies on `__INO_T_MATCHES_INO64_T`. This is a glibc macro not defined by other libcs. Hence, musl takes the LFS-compatibility code path. Then `__ino_t` also is a glibc-ism not defined on musl and that results in:

    matchpathcon.c:270:47: error: ‘__ino_t’ undeclared here (not in a function); did you mean ‘ino_t’?
      270 | static_assert(sizeof(unsigned long) == sizeof(__ino_t), "inode size mismatch");
          |                                               ^~~~~~~
          |                                               ino_t

I'm not sure what the solution here is and the answer likely depends on whether we want ABI duality for non-glibc systems. From a purely Debian-centered point of view, the ABI duality is only relevant to glibc, but I cannot speak for non-Debian consumers of libselinux.

For starters, I suggest adding back the `__BITS_PER_LONG < 64` condition (keeping the added `!defined(__INO_T_MATCHES_INO64_T)`) condition. Doing so immediately fixes the musl build on 64 bit architectures as it opts out of the compatibility code that is not needed there.

An option for improving the situation on 32bit builds would be wrapping the `static_assert` about `__ino_t` in an `#ifdef __GLIBC__`. At that point we'd have fixed all but x32 musl, which would still be wrong. I doubt there are many x32 musl users, so that may be good enough.

**Comment by helmutg** [comment]
On `arc` with glibc in Debian, I am seeing

```
In file included from matchpathcon.c:1:
matchpathcon.c:270:1: error: static assertion failed: "inode size mismatch"
  270 | static_assert(sizeof(unsigned long) == sizeof(__ino_t), "inode size mismatch");
      | ^~~~~~~~~~~~~
```

That's precisely the same failure that buildroot sees for `arc` with glibc.
