### PR TITLE
libselinux/utils/getseuser.c: fix build with gcc 4.8

### PR DESCRIPTION
**Pull request by ffontaine**
Fix the following build failure with gcc 4.8 which is raised since version 3.2 and https://github.com/SELinuxProject/selinux/commit/156dd0de5cad31e7d437c64e11a8aef027f0a691

```
getseuser.c:53:2: error: 'for' loop initial declarations are only allowed in C99 mode
  for (int i = 0; i < n; i++)
  ^
```

Fixes:
 - http://autobuild.buildroot.org/results/37eb0952a763256fbf6ef3c668f6c95fbdf2dd35

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Review by Vlastimilstanik — APPROVED** [review]

**Comment by fishilico** [comment]
Thanks for the patch. Nevertheless to contribute to this project, patches are required to be sent for review to SELinux mailing list at selinux@vger.kernel.org (see https://github.com/SELinuxProject/selinux/blob/master/CONTRIBUTING.md)

If you can't do this for some reason, I can do it for you.

**Comment by ffontaine** [comment]
Done

**Comment by fishilico** [comment]
Merged as https://github.com/SELinuxProject/selinux/commit/4859b738136ef8889fbb71a166cfec8d313ba4e0 (from mailing list message https://lore.kernel.org/selinux/20210701170619.96954-1-fontaine.fabrice@gmail.com/). Thanks!
