### ISSUE TITLE
libselinux + libsemanage: incompatibility with swig 4.3.0

### ISSUE THREAD

**Issue by ca-hu** [SELinuxProject/selinux#447]
swig 4.3.0 will change the `SWIG_Python_AppendOutput` function signature, see:

https://github.com/swig/swig/blob/ea8aa84b28d67e28c3a4c9a798af7077b7a02cb0/CHANGES.current#L359

That means libselinux and libsemanage do not build with swig 4.3.0 anymore.

see logs:
[build_failure_libselinux.log](https://github.com/user-attachments/files/17365112/build_failure_libselinux.log)
[build_failure_libsemanage.log](https://github.com/user-attachments/files/17365114/build_failure_libsemanage.log)

```
[   14s] selinuxswig_python_wrap.c: In function ‘_wrap_security_compute_user’:
[   14s] selinuxswig_python_wrap.c:11499:17: error: too few arguments to function ‘SWIG_Python_AppendOutput’
[   14s] 11499 |     resultobj = SWIG_Python_AppendOutput(resultobj, plist);
[   14s]       |                 ^~~~~~~~~~~~~~~~~~~~~~~~
[   14s] selinuxswig_python_wrap.c:1248:1: note: declared here
[   14s]  1248 | SWIG_Python_AppendOutput(PyObject* result, PyObject* obj, int is_void) {
[   14s]       | ^~~~~~~~~~~~~~~~~~~~~~~~
[   14s] selinuxswig_python_wrap.c: In function ‘_wrap_security_compute_user_raw’:
[   14s] selinuxswig_python_wrap.c:11570:17: error: too few arguments to function ‘SWIG_Python_AppendOutput’
[   14s] 11570 |     resultobj = SWIG_Python_AppendOutput(resultobj, plist);
[   14s]       |                 ^~~~~~~~~~~~~~~~~~~~~~~~
[   14s] selinuxswig_python_wrap.c:1248:1: note: declared here
[   14s]  1248 | SWIG_Python_AppendOutput(PyObject* result, PyObject* obj, int is_void) {
[   14s]       | ^~~~~~~~~~~~~~~~~~~~~~~~
[   14s] selinuxswig_python_wrap.c: In function ‘_wrap_security_get_boolean_names’:
[   14s] selinuxswig_python_wrap.c:12470:17: error: too few arguments to function ‘SWIG_Python_AppendOutput’
[   14s] 12470 |     resultobj = SWIG_Python_AppendOutput(resultobj, list);
[   14s]       |                 ^~~~~~~~~~~~~~~~~~~~~~~~
[   14s] selinuxswig_python_wrap.c:1248:1: note: declared here
[   14s]  1248 | SWIG_Python_AppendOutput(PyObject* result, PyObject* obj, int is_void) {
[   14s]       | ^~~~~~~~~~~~~~~~~~~~~~~~
[   14s] error: command '/usr/bin/gcc' failed with exit code 1
```

see:
https://bugzilla.suse.com/show_bug.cgi?id=1231587

**Comment by bachradsusi** [comment]
https://lore.kernel.org/selinux/20241016184825.200567-1-lautrbach@redhat.com/T/#t
